CREATE TABLE banco.movimientos_tarjetas (
  ID_MOVIMIENTO int DEFAULT NULL,
  ID_CLIENTE int DEFAULT NULL,
  NRO_TARJETA char(16) DEFAULT NULL,
  FECHA_MOV date DEFAULT NULL,
  TIPO_MOV char(1) DEFAULT NULL,
  MONTO decimal(12,2) DEFAULT 0
);


CREATE TABLE banco.cuotas_hipoteca (
    ID_CLIENTE INT,
    ID_HIPOTECA INT,
    N_CUOTA INT,
    FECHA DATE,
    ESTADO VARCHAR(20),
    MONTO_CUOTA DECIMAL(12,2),
    UNIQUE (ID_HIPOTECA, ID_CLIENTE, N_CUOTA)
);

CREATE TABLE banco.movimientos_ctactes (
  ID_MOV_CTA int ,
  ID_CTACTES int ,
  ID_CLIENTE int ,
  FECHA_MOV date ,
  TIP_MOV char(1),
  IMPORTE_MOV decimal(12,2) DEFAULT NULL,
  SALDO_ACTUAL decimal(12,2) DEFAULT NULL
)
