CREATE TABLE `movimientos_tarjetas` (
  `ID_MOVIMIENTO` int DEFAULT NULL,
  `ID_CLIENTE` int DEFAULT NULL,
  `NRO_TARJETA` char(16) DEFAULT NULL,
  `FECHA_MOV` date DEFAULT NULL,
  `TIPO_MOV` char(1) DEFAULT NULL,
  `MONTO` decimal(12,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
